#!/bin/bash
# Auto-generated script to re-run failed tests
# Each line runs a single failed test method
#
# Usage: Run from the root of a runtime repository (runtime or runtime2)
#   bash ../wasm-team/scripts/run-all-failed-tests.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.MeterFactoryIntegrationTest.SocketsHttpHandler_Configured
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.MeterFactoryIntegrationTest.SocketsHttpHandler_HasExisting_Unchanged
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_Parameterless_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.DefaultPrimaryHandler_RespectsHandlerLifetime
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.DefaultPrimaryHandler_NamedClient_RespectsHandlerLifetime
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByAction_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByBuilder_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AllIntProperties
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AllBoolProperties
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AllTimeSpanProperties
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AutomaticDecompression
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_KeepAlivePingPolicy
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ChainingActionAfterIConfiguration_Updates
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ChainingIConfigurationAfterAction_Updates
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_PresetSocketsHttpHandler_Updates
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.Tests" "src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/Microsoft.Extensions.Options.Tests.csproj" -m Microsoft.Extensions.Options.Tests.OptionsMonitorTest.InstantiatesOnlyOneOptionsInstance
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.Tests" "src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/Microsoft.Extensions.Options.Tests.csproj" -m Microsoft.Extensions.Options.Tests.OptionsTest.Configure_GetsNullableOptionsFromConfiguration
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.SourceGeneration.Unit.Tests" "src/libraries/Microsoft.Extensions.Options/tests/SourceGeneration.Unit.Tests/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.csproj" -m Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.SourceGeneration.Unit.Tests" "src/libraries/Microsoft.Extensions.Options/tests/SourceGeneration.Unit.Tests/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.csproj" -m Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestGeneratedRangeAttributeThreadSafety
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.RuntimeFilterChange
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.Refresh_RemoveSwitch
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.Refresh_ChangeSwitch
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.Refresh_RemoveSource
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.ConfigWithEvents_RuntimeListener
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.AllTypes
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.Switch_MissingValue_Throws
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.UnsupportedAttribute_Throws
"$SCRIPT_DIR/run-test-suite.sh" "System.Net.Http.Json.Functional.Tests" "src/libraries/System.Net.Http.Json/tests/FunctionalTests/System.Net.Http.Json.Functional.Tests.csproj" -m System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.GetFromJsonAsync_EnforcesMaxResponseContentBufferSize
"$SCRIPT_DIR/run-test-suite.sh" "System.Net.Http.Json.Functional.Tests" "src/libraries/System.Net.Http.Json/tests/FunctionalTests/System.Net.Http.Json.Functional.Tests.csproj" -m System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.GetFromJsonAsync_EnforcesTimeout
"$SCRIPT_DIR/run-test-suite.sh" "System.Net.Http.Json.Functional.Tests" "src/libraries/System.Net.Http.Json/tests/FunctionalTests/System.Net.Http.Json.Functional.Tests.csproj" -m System.Net.Http.Json.Functional.Tests.HttpClientJsonExtensionsTests.GetFromJsonAsAsyncEnumerable_EnforcesTimeout
"$SCRIPT_DIR/run-test-suite.sh" "System.Net.Mail.Functional.Tests" "src/libraries/System.Net.Mail/tests/Functional/System.Net.Mail.Functional.Tests.csproj" -m System.Net.Mail.Tests.MailMessageTest.SendMailMessageTest
"$SCRIPT_DIR/run-test-suite.sh" "System.Net.Mail.Functional.Tests" "src/libraries/System.Net.Mail/tests/Functional/System.Net.Mail.Functional.Tests.csproj" -m System.Net.Mail.Tests.MailMessageTest.SentSpecialLengthMailAttachment_Base64Decode_Success
"$SCRIPT_DIR/run-test-suite.sh" "System.Net.Primitives.Functional.Tests" "src/libraries/System.Net.Primitives/tests/FunctionalTests/System.Net.Primitives.Functional.Tests.csproj" -m System.Net.Primitives.Functional.Tests.SocketAddressTest.ToString_UnsupportedFamily_Throws
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_TypeWithDateTimePropertyAsXmlTime
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_Struct
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_Nullables
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_DerivedClasses
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_TypeWithDefaultTimeSpanProperty
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_TypeWithDateTimeOffsetProperty
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_TimeOnlyParseErrors
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_TypeWithDateOnlyAndTimeOnly
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_XsdDate_With_DateOnly_And_DateTime
"$SCRIPT_DIR/run-test-suite.sh" "System.Xml.XmlSerializer.ReflectionOnly.Tests" "src/libraries/System.Private.Xml/tests/XmlSerializer/ReflectionOnly/System.Xml.XmlSerializer.ReflectionOnly.Tests.csproj" -m XmlSerializerTests.Xml_XsdTime_With_TimeOnly_And_DateTime
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.ComVariantMarshallerTests.UnknownWrapper_Of_GeneratedComInterfaceType_Marshals_To_UNKNOWN
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_NormalDelegateNonGeneric_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledDelegateNonGeneric_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_NormalDelegateGeneric_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledDelegateGeneric_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledOpenStaticDelegate
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.GetFunctionPointerForDelegateTests.GetFunctionPointerForDelegate_MarshalledClosedStaticDelegate
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_ValidInterface_Success
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.QueryInterfaceTests.QueryInterface_NoSuchInterface_Success
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.AddRefTests.AddRef_ValidPointer_Success
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.InteropServices.Tests" "src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System.Runtime.InteropServices.Tests.csproj" -m System.Runtime.InteropServices.Tests.ReleaseTests.Release_ValidPointer_Success
"$SCRIPT_DIR/run-test-suite.sh" "System.IO.Tests" "src/libraries/System.Runtime/tests/System.IO.Tests/System.IO.Tests.csproj" -m System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Extensions.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Extensions.Tests/System.Runtime.Extensions.Tests.csproj" -m System.Tests.AppDomainTests.MonitoringIsEnabled
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DoubleTests_GenericMath.ConvertToIntegerTest
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_ValueTypeParameterWithExplicitValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_DateTimeParameterWithMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DateTimeAndCustomConstantAttribute_DateTimeParameterWithMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_CustomConstantAndDateTimeAttribute_DateTimeParameterWithMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_CustomConstantAttribute_DateTimeParameterWithMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_DateTimeParameterWithExplicitValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_DecimalParameterWithAttributeAndMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DecimalAndCustomConstantAttribute_DecimalParameterWithAttributeAndMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_CustomConstantAndDecimalAttribute_DecimalParameterWithAttributeAndMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_CustomConstantAttribute_DecimalParameterWithAttributeAndMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_DecimalParameterWithAttributeAndExplicitValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_DecimalParameterWithMissingValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_DecimalParameterWithExplicitValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DelegateTests.DynamicInvoke_DefaultParameter_NullableIntWithExplicitValue
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.HalfTests_GenericMath.ParseValidStringTest
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.HalfTests_GenericMath.ParseValidSpanTest
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.SingleTests_GenericMath.ConvertToIntegerTest
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DateTimeTests.GetObjectData_Invoke_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Ctor_IntArray
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Ctor_IntSpan
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Ctor_Int_Int_Int_Bool_Byte
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Add_Overflows_ThrowsOverflowException
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Remainder
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Round_Digits_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Round_DigitsMode_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Subtract
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.DecimalTests.Subtract_Invalid
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.UInt128Tests.CompareTo_Other_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.UInt128Tests.Parse_Valid
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.Int128Tests.CompareTo_Other_ReturnsExpected
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.Int128Tests.Parse_Valid
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.Int128Tests.Parse_Span_Valid
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Tests.Int128Tests.Parse_Utf8Span_Valid
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Runtime.Tests.JitInfoTests.JitInfoCurrentThreadIsPopulated
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Reflection.Tests.ModuleTests.FullyQualifiedName
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Reflection.Tests.ModuleTests.Name
"$SCRIPT_DIR/run-test-suite.sh" "System.Runtime.Tests" "src/libraries/System.Runtime/tests/System.Runtime.Tests/System.Runtime.Tests.csproj" -m System.Runtime.CompilerServices.Tests.RuntimeFeatureTests.DynamicCode_Jit
"$SCRIPT_DIR/run-test-suite.sh" "System.Threading.Tasks.Tests" "src/libraries/System.Runtime/tests/System.Threading.Tasks.Tests/System.Threading.Tasks.Tests.csproj" -m System.Threading.Tasks.Tests.TaskContinueWithTests.LongContinuationChain_ContinueWith_DoesNotStackOverflow
