#!/bin/bash
# Auto-generated script to re-run failed tests
# Each line runs a single failed test method
#
# Usage: Run from the root of a runtime repository (runtime or runtime2)
#   bash ../wasm-team/scripts/run-all-failed-tests.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.MeterFactoryIntegrationTest.SocketsHttpHandler_Configured
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.MeterFactoryIntegrationTest.SocketsHttpHandler_HasExisting_Unchanged
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_Parameterless_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.DefaultPrimaryHandler_RespectsHandlerLifetime
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.DefaultPrimaryHandler_NamedClient_RespectsHandlerLifetime
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByAction_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByBuilder_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_Success
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AllIntProperties
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AllBoolProperties
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AllTimeSpanProperties
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_AutomaticDecompression
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ConfiguredByIConfiguration_KeepAlivePingPolicy
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ChainingActionAfterIConfiguration_Updates
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_ChainingIConfigurationAfterAction_Updates
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Http.Tests" "src/libraries/Microsoft.Extensions.Http/tests/Microsoft.Extensions.Http.Tests/Microsoft.Extensions.Http.Tests.csproj" -m Microsoft.Extensions.Http.SocketsHttpHandlerConfigurationTest.UseSocketsHttpHandler_PresetSocketsHttpHandler_Updates
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.Tests" "src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/Microsoft.Extensions.Options.Tests.csproj" -m Microsoft.Extensions.Options.Tests.OptionsMonitorTest.InstantiatesOnlyOneOptionsInstance
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.Tests" "src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/Microsoft.Extensions.Options.Tests.csproj" -m Microsoft.Extensions.Options.Tests.OptionsTest.Configure_GetsNullableOptionsFromConfiguration
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.SourceGeneration.Unit.Tests" "src/libraries/Microsoft.Extensions.Options/tests/SourceGeneration.Unit.Tests/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.csproj" -m Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes
"$SCRIPT_DIR/run-test-suite.sh" "Microsoft.Extensions.Options.SourceGeneration.Unit.Tests" "src/libraries/Microsoft.Extensions.Options/tests/SourceGeneration.Unit.Tests/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.csproj" -m Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestGeneratedRangeAttributeThreadSafety
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.RuntimeFilterChange
"$SCRIPT_DIR/run-test-suite.sh" "System.Diagnostics.TraceSource.Config.Tests" "src/libraries/System.Diagnostics.TraceSource/tests/System.Diagnostics.TraceSource.Config.Tests/System.Diagnostics.TraceSource.Config.Tests.csproj" -m System.Diagnostics.TraceSourceConfigTests.ConfigurationTests.Refresh_RemoveSwitch
